### ISSUE TITLE
Can this be made to work with IonIcons Javascript/SVG approach

### ISSUE THREAD

**Issue by hades200082** [denta/BG-Icon-Picker#11]
IonIcons Javascript/SVG approach lazyloads SVG icons instead of using CSS & fonts.

**Comment by bgunnarsson** [comment]
I think your looking for something more like this: https://our.umbraco.com/packages/backoffice-extensions/svg-icon-picker/ - If that is not what you're looking for then that is a perfect time to start a new package! If you want to collab on it, I'm more than happy to do so,.

BG: Icon Picker will only be for icon fonts, at least for now.

**Comment by hades200082** [comment]
Unfortunately, that wouldn't work for two reasons:

1. I'm using 8.1 and that's for 7 :(
2. I don't have a sprite-sheet to give it.

Ionic just gives a JS file to include. You put markup in your HTML like `<ion-icon name="arrow-up"></ion-icon>` and the JS takes care of lazy-loading the single SVG that's needed - no sprites involved.

Ionic does have a CSS/Font version, but the lazy-loaded SVGs are far better for page performance. If I use the CSS/Font in the back-office, does your package allow me to specify only a part of the CSS selector to return as the icon name?

If so then I could still use the JS/SVG version on the front-end of the site.

**Comment by bgunnarsson** [comment]
Feel free to test it out. I don't see why this would not work with the correct regex and icon pattern settings in the datatype

**Comment by bgunnarsson** [comment]
The regex I use for icon fonts extracts everything that has the pattern "icn-icon-name:before" in a stylesheet. If Ionic does have a stylesheet with that icon font version then I don't see why it would not work.

I'm all for adding new features to this package so if you find a way to implement this, please feel free to share it with me so I/we can implement it into the package if needed.

Edit:
If the icons from the icon font version has a stylesheet and you can add it to the markup with an "i" tag or similar then this will work.

**Comment by hades200082** [comment]
Ionic uses the following format for it's CSS selectors...

- `.ion-ios-arrow-up:before`
- `.ion-md-arrow-up:before`

This is the same icon, just a different style/svg ios and for material design.

Ideally, I'd like to have the selector return just the `arrow-up` bit of the selector and leave the selection of ios/md up to the front-end ... alternatively, having it return `ios-arrow-up` and/or `md-arrow-up` and listing the two styles in the selector would also be acceptable.

Is this possible?

**Comment by bgunnarsson** [comment]
Yes this is possible. In the datatype settings put this regex into the input field: (ion-[^:]*?):before

Then in your view you would have to use a regex to exclude the "ion-" part from the string that the picker returns. I'm no regex expert but I think this will get you started: [Regex replace function with Razor](https://stackoverflow.com/questions/8847987/regex-replace-function-with-razor) - given that you're using a razor view

**Comment by hades200082** [comment]
Great, thanks. I'll give it a go.

**Comment by bgunnarsson** [comment]
Let me know how this goes! :)

**Comment by bgunnarsson** [comment]
I'm closing this issue. Let me know if you get this working.
