### ISSUE TITLE
Installing from Developer > Packages section installs old version

### ISSUE THREAD

**Issue by greystate** [denta/BG-Icon-Picker#12]
When I install BG Icon Picker from within Umbraco 7's Packages installer, I get a version that doesn't work correctly (only show a single icon, like e.g. #7 )

It reports itself as version 1.0.6 which is also the latest downloadable version from Our Umbraco.

**Comment by bgunnarsson** [comment]
Hmmm thats weird, have you tried installing through nuget? The package words flawlessy for me.

Could you be so kind to tell me what version of Umbraco you're using? (the whole version number down to the minor version e.g. 7.15.3)

**Comment by greystate** [comment]
No, haven't tried Nuget (can't do that - I'm on a Mac using Umbraco Cloud).

It's version 7.15.2 or 7.15.3 (Umbraco Cloud auto-patched from .2 to .3 and I don't remember if that was before or after I installed the package).

I'm guessing the problem is that the OurUmbraco package may be missing those files, or may just be a version behind, content-wise?

**Comment by greystate** [comment]
Btw: I've already fixed it by grabbing all the source files and put the newer ones in manually, and everything works great!

Just wanted to make sure you were alerted to the fact, if someone else tried to install from the backoffice.

**Comment by bgunnarsson** [comment]
Ok thanks for letting me know, I was sure I built a new version of the v7 package but I'll definitely be updating that tomorrow. Thanks again!
