### ISSUE TITLE
First icon gets skipped

### ISSUE THREAD

**Issue by snoek8** [denta/BG-Icon-Picker#24]
Inside the while loop in bgPicker.dialog.controller.js you get the next match before the first one is added to the array so the first one gets skipped. You can easily fix it changing it to this:

`if (hasMatches) {
				var match = styleRegex.exec(response.data);

				while (match !== null) {
					// check if match has populated array
					if (match !== null && match.length > 1) {
						//c heck if array already contains match and not on exclude list
						if (!(matches.indexOf(match[1]) > 0)) {
							matches.push(match[1]);
							hasMatches = true;
						}
					}

            match = styleRegex.exec(response.data);
				}
			}`

**Comment by imoshep** [comment]
Hi, this is still here (on version 1.0.1). I reached the same conclusion on the fix.
