### ISSUE TITLE
Icons with multiple classes fail to render in the back office.

### ISSUE THREAD

**Issue by readingdancer** [denta/BG-Icon-Picker#3]
If you have an icon specified with more than one class it fails to render in the back office.

E.g.

icon.color

This is because the UI adds this to the HTML class attribute with the dot instead of a space, I have created a pull request to fix this issue.

**Comment by bgunnarsson** [comment]
I'll get on it. Thanks for your help!

**Comment by readingdancer** [comment]
I thought you'd disappeared from the planet, I tried to find your contact details but couldn't find them. Glad you've now seen it and Yay... it's merged :)

**Comment by bgunnarsson** [comment]
Haha yeah I just didn't check my notifications for a while. I'll be sure to fix that. Thanks again for your help!
