### ISSUE TITLE
Addition of a property converter for Models builder

### ISSUE THREAD

**Issue by Matthew-Wise** [denta/BG-Icon-Picker#4]
Hi,

Just about to write a converter for it as we use models builder. Just wanted to raise an issue in case someone else needs it.

Ill add it as a reply shortly  and look to add it properly at a later date

Matt

**Comment by Matthew-Wise** [comment]
Nothing more than telling models builder its a string instead of an object.
```c#
    [PropertyValueType(typeof(string))]
    public class BgIconPickerValueConverter : PropertyValueConverterBase
    {
        public override bool IsConverter(PublishedPropertyType propertyType)
        {
            return propertyType.PropertyEditorAlias.Equals("bgIconPicker");
        }
    }
```

**Comment by bgunnarsson** [comment]
Hi @Matthew-Wise this looks promising, I'll add it to the readme, thank you for your help!
