### ISSUE TITLE
Picker does not work in Umbraco version 8.0.0

### ISSUE THREAD

**Issue by bgunnarsson** [denta/BG-Icon-Picker#5]
I'm working on a fix so the picker will work with umbraco version 8+, it will probably be a seperate version package since there are a few changes to how the angular fetch is handled. I haven't tested the fix in version below version 8 but I'll be doing so when I finish the fix.

**Comment by bgunnarsson** [comment]
I've almost finished making the picker work in V8, will be testing in both V8 and V7 this weekend and will hopefully release it on sunday.

**Comment by marcoteodoro** [comment]
@bgunnarsson is there a V8 working version already?

**Comment by bgunnarsson** [comment]
@marcoteodoro - Almost! I'm figuring out why V8 does not find regex matches in my stylesheet, after that I'll mark this as closed and this repository will change to include both V7 and V8.

**Comment by bgunnarsson** [comment]
Fixed this bug and now I have to fix the styling and its done.

**Comment by marcoteodoro** [comment]
@bgunnarsson i will take a look probably next week. Thanks for this

**Comment by bgunnarsson** [comment]
@marcoteodoro Thanks, just look at the readme for further information when you check back :)

**Comment by bgunnarsson** [comment]
The v8 package is live on nuget and our.umbraco.org. The styling is not perfect, the next version will fix that.
