### ISSUE TITLE
The first icon in the CSS is not shown.

### ISSUE THREAD

**Issue by met67** [denta/BG-Icon-Picker#7]
The first icon that in the CSS that matches the regexp is excluded from the icon list.

**Comment by bgunnarsson** [comment]
Thanks for noticing! Don´t you get an empty space if this is implemented?

**Comment by bgunnarsson** [comment]
For me and my icon fonts there's always an empty space for the first one, I'll boot up this project and check it out.

**Comment by met67** [comment]
Don't know... I don't have any empty space.
I use https://icomoon.io/app/ to generate my icon fonts and the result is fine...
![Immagine](https://user-images.githubusercontent.com/4471785/57243170-b728e900-7035-11e9-8598-b21879f17a74.png)
(In my font selection the 500px icon is duplicated at the moment …)

**Comment by bgunnarsson** [comment]
Ok I'll dive deeper tonight, thanks again.
